In [ ]:

- title: Pandas Useful Tricks
- author: Alex
- date: 2022-02-20
- category: python
- tags: jupyter


### Introduction

Here I want to share some useful pandas methods. The input data comes from module pydataset that comes with a bunch of popular dataset. 

In [4]:
import pandas as pd
from pydataset import data

### Create Contingency Table

Columns representing Hair , Eye color used to make a cross-table. Going from HairEyeColor table individuals to group counts done as follows.

In [5]:

_input= data('HairEyeColor')

contingency_ds= pd.crosstab(_input["Hair"], _input["Eye"])

contingency_ds

Eye    Blue  Brown  Green  Hazel
Hair                            
Black     2      2      2      2
Blond     2      2      2      2
Brown     2      2      2      2
Red       2      2      2      2

### Slicing
When input looks like that:

In [6]:
_input.head(7)

Hair    Eye   Sex  Freq
1  Black  Brown  Male    32
2  Brown  Brown  Male    53
3    Red  Brown  Male    10
4  Blond  Brown  Male     3
5  Black   Blue  Male    11
6  Brown   Blue  Male    50
7    Red   Blue  Male    10

To get a subpart of the df is as simple as: 

In [7]:
df_sliced = _input.iloc[0:5, 0:2] # rows then columns indices passed to the iloc
df_sliced

Hair    Eye
1  Black  Brown
2  Brown  Brown
3    Red  Brown
4  Blond  Brown
5  Black   Blue

### Transpose
To switch rows by columns you call method `.T` on `df`.

In [8]:
df_T= df_sliced.T
df_T

1      2      3      4      5
Hair  Black  Brown    Red  Blond  Black
Eye   Brown  Brown  Brown  Brown   Blue

### Pivot Table
Pivot is useful to make a report on relevant features, when you get counts of relevant values groupped by selected columns.  

In [9]:
_input.head()

Hair    Eye   Sex  Freq
1  Black  Brown  Male    32
2  Brown  Brown  Male    53
3    Red  Brown  Male    10
4  Blond  Brown  Male     3
5  Black   Blue  Male    11

In [10]:
pivot = _input.pivot_table(index='Hair', columns=['Sex','Eye'], values='Freq')

pivot

Sex   Female                   Male                  
Eye     Blue Brown Green Hazel Blue Brown Green Hazel
Hair                                                 
Black      9    36     2     5   11    32     3    10
Blond     64     4     8     5   30     3     8     5
Brown     34    66    14    29   50    53    15    25
Red        7    16     7     7   10    10     7     7

In [11]:
pivot2 = _input.pivot_table(index='Hair', columns=['Sex'], values='Freq')

pivot2

Sex    Female   Male
Hair                
Black   13.00  14.00
Blond   20.25  11.50
Brown   35.75  35.75
Red      9.25   8.50

### apply() a Custom Function

### Loading the Data into df
In this example I will manipulate data that comes from additional dependency: scikit-learn.
##### Inspecting the Data


In [12]:
from sklearn import datasets
iris = datasets.load_iris()

print(iris.data)
print(iris.target)
print(iris.DESCR)
type(data)

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.2]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.6 1.4 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.  3.3 1.4 0.2]
 [7.  3.2 4.7 1.4]
 [6.4 3.2 4.5 1.5]
 [6.9 3.1 4.

function

In [13]:
print(iris.DESCR)

.. _iris_dataset:

Iris plants dataset
--------------------

**Data Set Characteristics:**

    :Number of Instances: 150 (50 in each of three classes)
    :Number of Attributes: 4 numeric, predictive attributes and the class
    :Attribute Information:
        - sepal length in cm
        - sepal width in cm
        - petal length in cm
        - petal width in cm
        - class:
                - Iris-Setosa
                - Iris-Versicolour
                - Iris-Virginica
                
    :Summary Statistics:

    ============== ==== ==== ======= ===== ====================
                    Min  Max   Mean    SD   Class Correlation
    ============== ==== ==== ======= ===== ====================
    sepal length:   4.3  7.9   5.84   0.83    0.7826
    sepal width:    2.0  4.4   3.05   0.43   -0.4194
    petal length:   1.0  6.9   3.76   1.76    0.9490  (high!)
    petal width:    0.1  2.5   1.20   0.76    0.9565  (high!)
    ============== ==== ==== ======= ===== ===========

### Groupby
To apply groupby in pandas to get the count of each category, you can use the following code on dummy data:

In [2]:
import pandas as pd
import numpy as np

# categories
fruits = ['apple', 'banana', 'cherry', 'date', 'elderberry']

# total of 100 items
num_items = 100

# Randomly choose the number of items for each fruit type
counts = np.random.choice(range(1, num_items + 1), len(fruits), replace=False)
counts = counts / counts.sum() * num_items

# Create the data dictionary
data = {'group': [], 'attribute': []}

# Populate the data dictionary with random-sized groups
for count, fruit in zip(counts, fruits):
    data['group'].extend(np.repeat(fruit, int(count)))
    data['attribute'].extend(np.tile(fruit, int(count)))

df = pd.DataFrame(data)
# shuffle the DataFrame
df = df.sample(frac=1).reset_index(drop=True)

# Apply groupby and get the count of each type of fruit
fruit_counts = df.groupby('attribute').size().reset_index(name='count')
print(fruit_counts)

    attribute  count
0       apple     18
1      banana      9
2      cherry     21
3        date     26
4  elderberry     24


### Filter Data Frame
use boolean indexing to filter a df based on a particular value in a specific column:


In [3]:
import pandas as pd

# Assuming 'df' is your original DataFrame
# For example, let's say you have a column named 'column_x' and you want to filter based on a specific value, let's call it 'desired_value'

desired_value,desired_value2 = 'apple', 'banana'  # Replace this with the actual value you want to filter on
filtered_df = df[(df['attribute'] == desired_value)  | (df['attribute'] == desired_value2)] 

# Now, 'filtered_df' contains only the rows where 'column_x' has the value equal to 'desired_value'
filtered_df

group attribute
1    apple     apple
8    apple     apple
10  banana    banana
12  banana    banana
16   apple     apple
17  banana    banana
22   apple     apple
31   apple     apple
38  banana    banana
40   apple     apple
43   apple     apple
45   apple     apple
46   apple     apple
56  banana    banana
58   apple     apple
60   apple     apple
62   apple     apple
63  banana    banana
65   apple     apple
73   apple     apple
75   apple     apple
76   apple     apple
79   apple     apple
85   apple     apple
91  banana    banana
93  banana    banana
95  banana    banana

In [6]:
filtered_df.attribute.value_counts()

apple     18
banana     9
Name: attribute, dtype: int64

### pd.get_dummies

Of course I need to play with Titanic dataset and want to split class attribute into separate columns for first, second, and third class, 
I used pandas' get_dummies() function to create binary columns for each class. Then I add these binary columns to the original df. 
